# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-22 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='gay',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesbian',
        ),
        migrations.RemoveField(
            model_name='video',
            name='straight',
        ),
        migrations.AddField(
            model_name='video',
            name='gender',
            field=models.CharField(choices=[(0, 'Straight'), (1, 'Lesbian'), (2, 'Gay')], default=None, max_length=200),
        ),
    ]
