# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-22 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20170822_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Straight'), (1, 'Lesbian'), (2, 'Gay')]),
        ),
    ]
