# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-25 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='mood',
            field=models.IntegerField(choices=[(0, 'Soft'), (1, 'Intense'), (2, 'Rough')], default='0'),
        ),
    ]
