# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_video_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='topic',
            field=models.IntegerField(choices=[(0, 'Soft'), (1, 'Intense'), (2, 'Rough')], default='0'),
        ),
        migrations.AlterField(
            model_name='video',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Straight'), (1, 'Lesbian'), (2, 'Gay'), (3, 'Threesome (FMF)'), (4, 'Threesome (MMF)')]),
        ),
    ]
