# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20170830_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
