# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_video_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='race',
            field=models.IntegerField(choices=[(0, 'Interacial'), (1, 'White'), (2, 'Black'), (3, 'Asian'), (4, 'Latino'), (5, 'Other')], default=0),
            preserve_default=False,
        ),
    ]
