# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
