# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-01 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_video_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
