# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-01 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_video_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file_path',
        ),
    ]
